package test.util;

public class KeyCode {
	
	/** The unknown key. */
    public static final int KR_UNKNOWN = -1;

    /** Printable keys. */
    public static final int
        KR_SPACE         = 32,
        KR_APOSTROPHE    = 39,
        KR_COMMA         = 44,
        KR_MINUS         = 45,
        KR_PERIOD        = 46,
        KR_SLASH         = 47,
        KR_0             = 48,
        KR_1             = 49,
        KR_2             = 50,
        KR_3             = 51,
        KR_4             = 52,
        KR_5             = 53,
        KR_6             = 54,
        KR_7             = 55,
        KR_8             = 56,
        KR_9             = 57,
        KR_SEMICOLON     = 59,
        KR_EQUAL         = 61,
        KR_A             = 65,
        KR_B             = 66,
        KR_C             = 67,
        KR_D             = 68,
        KR_E             = 69,
        KR_F             = 70,
        KR_G             = 71,
        KR_H             = 72,
        KR_I             = 73,
        KR_J             = 74,
        KR_K             = 75,
        KR_L             = 76,
        KR_M             = 77,
        KR_N             = 78,
        KR_O             = 79,
        KR_P             = 80,
        KR_Q             = 81,
        KR_R             = 82,
        KR_S             = 83,
        KR_T             = 84,
        KR_U             = 85,
        KR_V             = 86,
        KR_W             = 87,
        KR_X             = 88,
        KR_Y             = 89,
        KR_Z             = 90,
        KR_LEFT_BRACKET  = 91,
        KR_BACKSLASH     = 92,
        KR_RIGHT_BRACKET = 93,
        KR_GRAVE_ACCENT  = 96,
        KR_WORLD_1       = 161,
        KR_WORLD_2       = 162;

    /** Function keys. */
    public static final int
        KR_ESCAPE        = 256,
        KR_ENTER         = 257,
        KR_TAB           = 258,
        KR_BACKSPACE     = 259,
        KR_INSERT        = 260,
        KR_DELETE        = 261,
        KR_RIGHT         = 262,
        KR_LEFT          = 263,
        KR_DOWN          = 264,
        KR_UP            = 265,
        KR_PAGE_UP       = 266,
        KR_PAGE_DOWN     = 267,
        KR_HOME          = 268,
        KR_END           = 269,
        KR_CAPS_LOCK     = 280,
        KR_SCROLL_LOCK   = 281,
        KR_NUM_LOCK      = 282,
        KR_PRINT_SCREEN  = 283,
        KR_PAUSE         = 284,
        KR_F1            = 290,
        KR_F2            = 291,
        KR_F3            = 292,
        KR_F4            = 293,
        KR_F5            = 294,
        KR_F6            = 295,
        KR_F7            = 296,
        KR_F8            = 297,
        KR_F9            = 298,
        KR_F10           = 299,
        KR_F11           = 300,
        KR_F12           = 301,
        KR_F13           = 302,
        KR_F14           = 303,
        KR_F15           = 304,
        KR_F16           = 305,
        KR_F17           = 306,
        KR_F18           = 307,
        KR_F19           = 308,
        KR_F20           = 309,
        KR_F21           = 310,
        KR_F22           = 311,
        KR_F23           = 312,
        KR_F24           = 313,
        KR_F25           = 314,
        KR_KP_0          = 320,
        KR_KP_1          = 321,
        KR_KP_2          = 322,
        KR_KP_3          = 323,
        KR_KP_4          = 324,
        KR_KP_5          = 325,
        KR_KP_6          = 326,
        KR_KP_7          = 327,
        KR_KP_8          = 328,
        KR_KP_9          = 329,
        KR_KP_DECIMAL    = 330,
        KR_KP_DIVIDE     = 331,
        KR_KP_MULTIPLY   = 332,
        KR_KP_SUBTRACT   = 333,
        KR_KP_ADD        = 334,
        KR_KP_ENTER      = 335,
        KR_KP_EQUAL      = 336,
        KR_LEFT_SHIFT    = 340,
        KR_LEFT_CONTROL  = 341,
        KR_LEFT_ALT      = 342,
        KR_LEFT_SUPER    = 343,
        KR_RIGHT_SHIFT   = 344,
        KR_RIGHT_CONTROL = 345,
        KR_RIGHT_ALT     = 346,
        KR_RIGHT_SUPER   = 347,
        KR_MENU          = 348,
        KR_LAST          = KR_MENU;

}
