package com.starworks.kronos.event;

public enum EventType {
	
    NONE,
    KEY_PRESSED,
    KEY_RELEASED,
    KEY_REPEATED,
    KEY_TYPED,
    MOUSE_PRESSED,
    MOUSE_RELEASED,
    MOUSE_MOVED,
    MOUSE_SCROLLED,
    WINDOW_RESIZED,
    WINDOW_CLOSED,
    WINDOW_MOVED,
    WINDOW_FOCUS_GAINED,
    WINDOW_FOCUS_LOST,
    WINDOW_MINIMIZED,
    WINDOW_RESTORED,
    WINDOW_MAXIMIZED,
    WINDOW_UNMAXIMIZED,
    WINDOW_REFRESHED;
}
